# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GUSBli0KnHtPnAk6RSoSyn5m4jgjRXh
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(r'Titanic-Dataset.csv')
df.head()

df.info()
df.describe()
df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

sns.boxplot(x=df['Fare'])
plt.title('Boxplot of Fare')
plt.show()

df.to_csv('titanic_cleaned.csv', index=False)
print("Cleaned data saved as 'titanic_cleaned.csv'")

sns.boxplot(x=df['Fare'])
plt.title('Boxplot of Fare')
plt.show()

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df['Fare'] >= lower_bound) & (df['Fare'] <= upper_bound)]

Q1_age = df['Age'].quantile(0.25)
Q3_age = df['Age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

df = df[(df['Age'] >= Q1_age - 1.5 * IQR_age) & (df['Age'] <= Q3_age + 1.5 * IQR_age)]

sns.boxplot(x=df['Fare'])
plt.title("Boxplot After Outlier Removal")
plt.show()